backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads" # Папка для загрузки медиафайлов
public_folder: "/uploads" # Публичная папка для медиафайлов

collections:
  - name: "englishDocs"
    label: "English Docs"
    folder: "content/en/docs"
    create: true
    nested:
      depth: 2
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Sub-Section", name: "sub_section", widget: "object", fields: [
        { label: "Title", name: "title", widget: "string" },
        { label: "Files", name: "files", widget: "list", fields: [
          { label: "Title", name: "title", widget: "string" },
          { label: "Body", name: "body", widget: "markdown" }
        ]}
      ]}
  - name: "russianDocs"
    label: "Russian Docs"
    folder: "content/ru/docs"
    create: true
    nested:
      depth: 2
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Sub-Section", name: "sub_section", widget: "object", fields: [
        { label: "Title", name: "title", widget: "string" },
        { label: "Files", name: "files", widget: "list", fields: [
          { label: "Title", name: "title", widget: "string" },
          { label: "Body", name: "body", widget: "markdown" }
        ]}
      ]}
